# Generated by Django 4.0.1 on 2022-02-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_tweetmodel_parent_alter_tweetmodel_likes'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='tweet_history',
            field=models.ManyToManyField(related_name='tweets', to='tweets.TweetModel'),
        ),
    ]
