# Generated by Django 4.0.1 on 2022-02-08 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profilemodel_tweet_history_followerrelation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'ordering': ['-timestamp']},
        ),
    ]
