# Generated by Django 4.0.1 on 2022-01-28 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweetmodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='tweetmodel',
            name='content',
            field=models.TextField(blank=True, max_length=300, null=True, validators=[django.core.validators.MaxLengthValidator]),
        ),
    ]
