# Generated by Django 4.0.1 on 2022-01-29 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0002_alter_tweetmodel_options_alter_tweetmodel_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tweetmodel',
            name='content',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
