# Generated by Django 4.0.1 on 2022-01-31 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0003_tweetmodel_user_alter_tweetmodel_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetLikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tweetmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='tweetmodel',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='tweet_user', through='tweets.TweetLikeModel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tweetmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweetlikemodel',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.tweetmodel'),
        ),
        migrations.AddField(
            model_name='tweetlikemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
